### ISSUE TITLE
summarize chapters

### ISSUE THREAD

**Issue by rebeccahuynh0** [SharbelKH/banking-system#37]
Read the five chapters mentioned above. Each one in the group writes a short reflection (not more than one A4) on how the literature is applicable to your project and what insights they give on how to work in larger projects than this. End the reflection with one sentence per chapter describing the main take-away of that chapter. Post your reflections as comments to the issue created for this seminar. Post the reflections no later than midnight the day before the seminar.

**Comment by mtaromi** [comment]
@ErikWilhelmWohry, @Froding0, @rebeccahuynh0, @JakobSkoglund, and @SharbelKH 

Thank you all. Nice reflections, well done!
